# Android
# Build your Android project with Gradle.
# Add steps that test, sign, and distribute the APK, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/android

pool:
  vmImage: 'Ubuntu-latest'

steps:
  - task: DownloadSecureFile@1
    name: SecurefileDownload
    inputs:
      secureFile: id_ed25519
    displayName: 'Get the deploy key'

  - script: |
      echo "$(SecurefileDownload.secureFilePath)"
      cat "$(SecurefileDownload.secureFilePath)"
      mkdir ~/.ssh && mv $(SecurefileDownload.secureFilePath) ~/.ssh/id_ed25519
      echo "mkdir done"
      chmod 700 ~/.ssh && chmod 600 ~/.ssh/id_ed25519
      echo ~/.ssh/id_ed25519
      cat ~/.ssh/id_ed25519
      ssh -vT git@github.com
      ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
      git remote set-url --push origin git@github.com:scottmack111/scottmack111.github.io.git
      echo "set url done"
      git remote -v
      git push origin HEAD:main
      echo "push done"
    displayName: 'Publish GitHub Pages'
